### ISSUE TITLE
Revise barrier/sync order and cross-reference

### ISSUE THREAD

**Issue by nspark** [gmegan/specification#45]
The opening text for `shmem_barrier_all` says:

> Registers the arrival of a PE at a barrier and blocks the PE until all other PEs arrive at the barrier and all local updates and remote memory updates on the default context are completed.

While the opening text for `shmem_barrier` says:

> Performs all operations described in the `shmem_barrier_all` interface but with respect to a subset of PEs defined by the active set.

As we update the specification for teams and add predefined teams like `SHMEM_TEAM_WORLD`, I think it makes more sense to specify the semantics for `shmem_team_barrier` and `shmem_barrier` (on active sets) first, then define `shmem_barrier_all` as `shmem_team_barrier(SHMEM_TEAM_WORLD)`. Further, we can do the same for the `shmem_sync` family of functions, and define the `shmem_barrier` family in terms of `shmem_team_sync` and `shmem_ctx_quiet`.

Semantically, this would be a no-op change with respect to OpenSHMEM 1.4, however, it would be a nontrivial textual change.

**Comment by gmegan** [comment]
The current PR #50 deprecates barrier altogether... Some issues with barrier under the current model:

- Allowing both team and context argument is a recipe for problems since the context should be mapped to only one team and any different team argument should cause the operation to fail, or the program to abort
- How to barrier on SHMEM_TEAM_SHARED? Or any team that isn't creating contexts explicitly for that matter? One would have to make a new team that can create contexts, then use that context instead of the default, just to get barrier support.

The current PR says that users should migrate away from barrier to use quiet followed by sync.

**Comment by gmegan** [comment]
Closed per merge of sync/barrier updates
