### ISSUE TITLE
Config params for team split and null config parameter

### ISSUE THREAD

**Issue by gmegan** [gmegan/specification#52]
Currently, there is no way to shorthand a team split when config params are not required.

It seems useful to support this notation:
`shmem_team_split_strided(SHMEM_TEAM_WORLD, 0, 2, shmem_n_pes(), 0, 0, &even_team);`
where we just want to make a team of the even PEs. 

The API currently says that passing 0 for config_flags means to use all fields in the config struct. It seems like this should be the opposite, where 0 means to use no fields, use all default config values, and ignore the config parameter.

For one, this change would mean that a shorthand for team creation, as above, would work. It would mean here that the team supports collectives and cannot make new contexts for threads since those are the default behaviors.

For two, suppose that a program written for version 1.X uses the 0 value to indicate the use of all fields, then the spec adds a new config field, `conf.number_of_bunnies` in version 1.Y. Now this program is indicating that the library should use the config field for `conf.number_of_bunnies`, which is never initialized in this older program, and there is no way for the library to detect that this value of the config struct is full of garbage. So it tries to create a team with 458974598 bunnies and fails with some message like `Bunnies need more carrots` that the programmer doesn't understand, since they didn't even know that OpenSHMEM 1.Y added bunnies.

**Comment by gmegan** [comment]
I am writing up examples for config and split and have started to ask myself why the split parameters are not part of the config struct...

**Comment by nspark** [comment]
🐰 🥕

**Comment by nspark** [comment]
IIRC, my initial thought was that when `config_max` was zero, the whole `config` argument would be used because the a `shmem_team_config_t` structure that was zero-initialized would represent the defaults. (This was for the "inversion" of the field `disable_collectives` vs. `enable_collectives`.) The intent was to support as terse a team creation as possible. I think you raise a good point that this isn't logically scalable and any subsequently-added field may result in undefined values for some fields when changing to newer OpenSHMEM versions.

If we invert the meaning of a zero-valued mask to the natural semantic -- as you say, that none of the `shmem_team_config_t` fields are used, a `NULL` value for `config` is permissible, and the default team parameters are used -- then I agree that we preserve the terse format with a cleaner semantic.
